[build]
functions = "functions/"
publish = "build/"
[build.environment]
REACT_APP_ADD_COMMENT_API = "/.netlify/functions/addComment"
REACT_APP_ADD_POST_API = "/.netlify/functions/addPost"
REACT_APP_DOWN_VOTE_API = "/.netlify/functions/downVote"
REACT_APP_LOGIN_USER_API = "/.netlify/functions/loginUser"
REACT_APP_POST_API = "/.netlify/functions/getPosts"
REACT_APP_REGISTER_USER_API = "/.netlify/functions/registerUser"
REACT_APP_UPLOAD_API = "/.netlify/functions/uploadImage"
REACT_APP_UP_VOTE_API = "/.netlify/functions/upVote"
REACT_APP_USER_POST_API = "/.netlify/functions/userPosts"

[dev]
autoLaunch = false
